version: '3'

x-spark-commom:
  &x-spark-commom
  image: docker.io/bitnami/spark:3.3
  environment:
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
  networks:
    - spark

services:
  spark:
    <<: *x-spark-commom
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark:7077
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./:/app

  spark-worker:
    <<: *x-spark-commom
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    volumes:
      - ./:/app

networks:
  spark:
    driver: bridge
