version: "3"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - 9092:9092
    volumes:
      - ./kafka_data:/bitnami:Z
      - ./:/app:Z
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"

  java:
    image: gradle:jdk17
    command: tail -f /dev/null
    tty: true
    volumes:
      - ./app:/app:Z
    working_dir: /app
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  opensearch:
    image: opensearchproject/opensearch:latest
    volumes:
      - ./opensearch_data:/usr/share/opensearch/data
    environment:
      discovery.type: single-noe
      plugins.security.disabled: 'true'
      compatibility.override_main_response_version: 'true'
    ports:
      - 9200:9200
      - 9600:9600

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '[http://opensearch:9200]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'